# Tensorflow Neural Network
A generic tensorflow framework implementation of classification task using neural networks

# Dataset
We use the iris dataset to perform a classification

In [1]:
from sklearn.datasets import load_iris
iris = load_iris()
X = iris.data
y = iris.target

In [2]:
from keras.utils import to_categorical
y = to_categorical(y)
y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [3]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8, test_size=0.2, random_state=42)

In [4]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

# Creating the Model
We create a sequential neural model with three layers

In [5]:
import tensorflow as tf
from tensorflow import keras
import numpy as np

keras.backend.clear_session()

In [6]:
model = keras.Sequential()
model.add(keras.layers.Dense(25, input_dim = 4, activation="relu"))
model.add(keras.layers.Dense(30, input_dim = 4, activation="relu"))
model.add(keras.layers.Dense(3, activation = tf.nn.softmax)) # Output

model.compile(loss=keras.losses.CategoricalCrossentropy(), optimizer="adam", metrics=['accuracy','mse'])

In [7]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 25)                125       
                                                                 
 dense_1 (Dense)             (None, 30)                780       
                                                                 
 dense_2 (Dense)             (None, 3)                 93        
                                                                 
Total params: 998 (3.90 KB)
Trainable params: 998 (3.90 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


# Evaluating
Fitting the data to the model and performing predictions

In [8]:
model.fit(X_train, y_train, epochs=100)

Epoch 1/100


4/4 [==============================] - 1s 5ms/step - loss: 1.1146 - accuracy: 0.3417 - mse: 0.2259
Epoch 2/100
4/4 [==============================] - 0s 5ms/step - loss: 1.0923 - accuracy: 0.3417 - mse: 0.2217
Epoch 3/100
4/4 [==============================] - 0s 5ms/step - loss: 1.0734 - accuracy: 0.3417 - mse: 0.2181
Epoch 4/100
4/4 [==============================] - 0s 4ms/step - loss: 1.0562 - accuracy: 0.3417 - mse: 0.2146
Epoch 5/100
4/4 [==============================] - 0s 3ms/step - loss: 1.0385 - accuracy: 0.3500 - mse: 0.2110
Epoch 6/100
4/4 [==============================] - 0s 5ms/step - loss: 1.0230 - accuracy: 0.4000 - mse: 0.2077
Epoch 7/100
4/4 [==============================] - 0s 4ms/step - loss: 1.0088 - accuracy: 0.5500 - mse: 0.2048
Epoch 8/100
4/4 [==============================] - 0s 3ms/step - loss: 0.9933 - accuracy: 0.6250 - mse: 0.2015
Epoch 9/100
4/4 [==============================] - 0s 3ms/step - loss: 0.9786 - accuracy: 0.6333 - mse: 0.1983

In [9]:
model.evaluate(X_test, y_test)

1/1 [==============================] - 0s 188ms/step - loss: 0.1412 - accuracy: 0.9667 - mse: 0.0245


[0.14121538400650024, 0.9666666388511658, 0.024457640945911407]

In [10]:
y_pred = model.predict(X_test)

1/1 [==============================] - 0s 102ms/step


In [11]:
y_pred = np.argmax(y_pred, axis=1)
y_pred

array([1, 0, 2, 1, 1, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0], dtype=int64)

In [12]:
y_test = np.argmax(y_test, axis=1)
y_test

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0], dtype=int64)

In [13]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)*100

96.66666666666667