# Tensorflow Neural Network
A generic tensorflow library implementation of classification task using neural networks

In [1]:
import tensorflow as tf
from tensorflow import keras
import numpy as np

keras.backend.clear_session()

# Creating the Model
We create a sequential neural model with three layers

In [2]:
model = keras.Sequential()
model.add(keras.layers.Dense(10, input_dim = 4, activation="relu"))
model.add(keras.layers.Dense(10, input_dim = 4, activation="relu"))
model.add(keras.layers.Dense(3)) # Output

model.compile(loss="categorical_crossentropy", optimizer="adam", metrics=['accuracy','mse'])

In [3]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 10)                50        
                                                                 
 dense_1 (Dense)             (None, 10)                110       
                                                                 
 dense_2 (Dense)             (None, 3)                 33        
                                                                 
Total params: 193 (772.00 Byte)
Trainable params: 193 (772.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


# Dataset
We use the iris dataset to perform a classification

In [4]:
from sklearn.datasets import load_iris
iris = load_iris()
X = iris.data
y = iris.target

In [5]:
from keras.utils import to_categorical
y = to_categorical(y)
y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [6]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8, test_size=0.2, random_state=42)

In [7]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

# Evaluating
Fitting the data to the model and performing predictions

In [8]:
model.fit(X_train, y_train, epochs=100)

Epoch 1/100


4/4 [==============================] - 1s 6ms/step - loss: 0.1156 - accuracy: 0.3250 - mse: 0.2914
Epoch 2/100
4/4 [==============================] - 0s 2ms/step - loss: 0.0212 - accuracy: 0.3250 - mse: 0.2939
Epoch 3/100
4/4 [==============================] - 0s 4ms/step - loss: 0.0016 - accuracy: 0.3250 - mse: 0.2976
Epoch 4/100
4/4 [==============================] - 0s 3ms/step - loss: 0.4039 - accuracy: 0.3250 - mse: 0.3004
Epoch 5/100
4/4 [==============================] - 0s 2ms/step - loss: 0.9407 - accuracy: 0.3250 - mse: 0.3023
Epoch 6/100
4/4 [==============================] - 0s 2ms/step - loss: 1.3432 - accuracy: 0.3250 - mse: 0.3036
Epoch 7/100
4/4 [==============================] - 0s 5ms/step - loss: 1.4775 - accuracy: 0.3250 - mse: 0.3045
Epoch 8/100
4/4 [==============================] - 0s 3ms/step - loss: 1.6118 - accuracy: 0.3333 - mse: 0.3051
Epoch 9/100
4/4 [==============================] - 0s 4ms/step - loss: 1.6118 - accuracy: 0.3333 - mse: 0.3055

In [9]:
model.evaluate(X_test, y_test)

1/1 [==============================] - 0s 236ms/step - loss: 1.6118 - accuracy: 0.3667 - mse: 0.3019


[1.611809492111206, 0.36666667461395264, 0.30190688371658325]

In [10]:
y_pred = model.predict(X_test)
y_pred

1/1 [==============================] - 0s 85ms/step


array([[-0.2226102 ,  0.09563205,  0.12615414],
       [-0.05973829,  0.05525262, -0.04003576],
       [-0.33064198,  0.17182815,  0.2881981 ],
       [-0.19987053,  0.09215912,  0.11972151],
       [-0.26318306,  0.12390835,  0.18407692],
       [-0.05567241,  0.04433105, -0.03359465],
       [-0.14258067,  0.06726323,  0.07046245],
       [-0.24486294,  0.1338878 ,  0.20375481],
       [-0.19556057,  0.10689768,  0.16093121],
       [-0.18217823,  0.08382298,  0.10449373],
       [-0.22338559,  0.11034253,  0.15457566],
       [-0.04721611,  0.04611145, -0.03190525],
       [-0.0430136 ,  0.05682261, -0.0374844 ],
       [-0.05201454,  0.04688117, -0.0333067 ],
       [-0.06093668,  0.06857578, -0.04589558],
       [-0.19828986,  0.08930365,  0.1106128 ],
       [-0.26153994,  0.12756383,  0.19052632],
       [-0.17921032,  0.08197213,  0.10226396],
       [-0.19404782,  0.08231185,  0.10009513],
       [-0.25952753,  0.13080613,  0.19906065],
       [-0.05879175,  0.04856309, -0.034

In [11]:
y_pred = np.argmax(y_pred, axis=1)
y_pred

array([2, 1, 2, 2, 2, 1, 2, 2, 2, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2, 2, 1, 2,
       1, 2, 2, 2, 2, 2, 1, 1], dtype=int64)

In [12]:
y_test = np.argmax(y_test, axis=1)
y_test

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0], dtype=int64)

In [13]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)*100

36.666666666666664